import '../styles/main.scss'
import Navbar from './components/navbar/Navbar';
import ClientOnly from './components/ClientOnly';
import { Roboto } from 'next/font/google'
import RegisterModal from './components/modals/RegisterModal';
import ToasterProvider from './providers/ToasterProvider';
import LoginModal from './components/modals/LoginModal';
import getCurrentUser from './actions/getCurrentUser';
import Footer from './components/Footer';


const roboto = Roboto({
  weight: ['100', '300','400', '500','700'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'HelsinkiRestaurantFinder',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser();


  return (
    <html lang="en">
      <body className={roboto.className}>
      <ClientOnly>
        <ToasterProvider/>
        <LoginModal/>
        <RegisterModal/>
        <Navbar currentUser={currentUser}/>
      </ClientOnly>
        <div className="childrenContainer">
          {children}
        </div>
        <Footer/>
      </body>
    </html>
  )
}
